[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3
  adafruit/RTClib @ ^2.1.4

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -D BOARD_SEEED_XIAO_ESP32C3
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3
  adafruit/RTClib @ ^2.1.4

[env:adafruit_qtpy_esp32s3_nopsram]
platform = espressif32
board = adafruit_qtpy_esp32s3_nopsram
framework = arduino
monitor_speed = 115200
build_flags =
  -D BOARD_ADAFRUIT_QTPY_ESP32S3
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3
  adafruit/RTClib @ ^2.1.4
